### PR TITLE
PR for issues #67, #69, #71 and #73

### PR DESCRIPTION
**Pull request by estilles**
Resolving the following issues
- #67 - [BUG] Input volume not set on activator message 
- #69 - [BUG] Bus Volume not being correctly set
- #71 - [FEATURE] Add dynamic variables and feedbacks for input/bus volumes that use a linear scale
- #73 - [BUG] InputAudio feedback not being called on activator message

### CODE REVIEW

**Comment by thedist** [comment]
I've tested your changes, and from a technical standpoint they work as you've described, but we would like you to make some changes before we can merge.

Adding a variable specifically for linear volume doubles the number of bus and input variables, creating a significantly longer variable list. Also the addition of new feedbacks pretty much replicates functionality but bases it off of different data.

A better option that has been discussed in the vMix channel on Companion Slack is to just have a new 'checkbox' type option in config that toggles on linear volume (and by default it would be off, so that volume is continued to be displayed the way it currently is).

Then rather than doubling up on variables/feedbacks, you can edit the existing variables/feedback to conditionally return volume, or linearVolume, based on the config option, for example:
`updateBuffer('variable', `bus_volume_${variableID.toLowerCase()}`, this.config.linearVolume ? volumeLinear : Math.round(volume));`

This would allow those who may want to display linear volume to do so, without bloating the list of variables/feedbacks and their update checks.

**Comment by estilles** [comment]
That's a very good point. I'll work on that and update my PR. Thanks for your comments.

**Comment by estilles** [comment]
I've updated the PR as requested, with one addition. I added to to update the variables volume related variables and corresponding feedbacks on configuration change. Without this addition the behavior of toggling the linear config option while the variables and bank feedback renamed the same seemed kinda odd.

**Review by thedist — APPROVED** [review]

**Comment by estilles** [comment]
@thedist ... Happy New Year! Any change these changes will be merged into companion soon?

**Pull request merged**
