### PR TITLE
New API Polling

### LINKED ISSUE #48: vMix get unstable / generate audio - video drops if using Companion
For some time now I noticed that vMix runs unstable or after several hours of events dropped frames and generates audio peaks. 

problem: 
- When using Companion (also externally on another system and only linked via network), frame drops or audio glitches occur after 1 hour of show. 
- If two independent Companion clients are used in the same network, the drops / glitches are much worse. 
- During a show the USB audio interface was lost.
- At one show it crashed vMix. 
- The problem occurs on different systems with different vMix versions. 

My current solution search. 
- Set up new windows
- test with ASIO driver from Steinberg and Focusrite and without
- Test with independent network 
- Test with other network cables
- Test with other NIC (USB to ethernet adapter)
- Test with different performance levels (complexity projects)
- Test with last version v.2.1.1
- Test with vMix 23.0.0.62 and newer
- Using various older Blackmagic Video drivers.

Conclusion:
- When I use Companion, I already have the first drops after 1 hour on all systems with the current version v2.0.1.
- After a reboot the system runs stable for about 1h. Systems that have been online for 24 hours have a much higher number of drops.
- Systems without Companion run for up to 14 hours without any drops.
- It does not matter whether the Companion Client runs on the PC or on another computer. (Same problem)

In the attachment I have some pictures of the glitches and a audio file.

https://we.tl/t-8CowvFNIqA

Gladly I will carry out further tests recommended by you. 

Best,
Jan

### PR DESCRIPTION
**Pull request by thedist**
Changed polling from the vMix HTTP REST API to the TCP connection that has previously been used just for sending commands. Performance within Companion is unchanged, but this should help combat the memory leaks in vMix. As HTTP requests are no longer required, the `got` library has been removed as a dependency, along with config fields for it.

Default API Poll time is unchanged, but anyone running vMix 23.0.0.66 or higher may be able to reduce the interval now that they have fixed their memory leaks which will result in faster feedback.

Potential issues:
The move to TCP socket for both feedback and commands means that this will be a breaking change for anyone who uses this module where a firewall blocks that TCP connection. I've asked on Companion Slack, and both broadcast and video engineering discords, and have no encountered anyone that this would impact. I don't expect anyone to actually be in this situation, as that would mean they would previously could see feedback but couldn't use any actions as those actions would have been blocked by the firewall too.

Resolves #48

### CODE REVIEW

**Comment by krocheck** [comment]
I disagree with the commend that this could break due to firewalls.  If that were the case, since commands are sent via TCP already, if that were blocked by a firewall then the module's actions wouldn't work.

Polling wise, I think you can go back to a default of 250ms?  Based on my read it doesn't seem like 0=disabled works anymore.  That's OK, but just make sure the help information is updated.

How much more testing do you need before dropping this?

**Comment by thedist** [comment]
> I disagree with the comment that this could break due to firewalls. If that were the case, since commands are sent via TCP already, if that were blocked by a firewall then the module's actions wouldn't work.

Sorry, perhaps I wasn't clear in my explanation. I was saying exactly that, that if their firewall already blocked the TCP Socket that they wouldn't have been able to use actions. That doesn't mean though that there may not potentially be a user who used this module purely for feedback from HTTP, and used the Generic HTTP Companion module for sending commands instead of actions within this vMix module. It's very niche, and I don't know of any users who use it like that, but nevertheless there is that potential to be a breaking change so I wanted to bring it up even if it's unlikely to have an impact.

>Polling wise, I think you can go back to a default of 250ms? Based on my read it doesn't seem like 0=disabled works anymore. That's OK, but just make sure the help information is updated.

I'll add back in the check to see if polling is set to 0, I removed it by mistake. As for the interval I'll change that to 250ms default, now that vMix has handled their memory leak. If we receive feedback from those who previously had issues at 100ms that it's now fine at 100ms after this patch we could always considering lowering it further in the future,

> How much more testing do you need before dropping this?

I just discovered an issue when testing with an extreme number of inputs where vMix splits messages into multiple parts. So before merging I need to implement a message buffer to handle multi-part messages for those edge cases.

**Comment by McHauge** [comment]
This is awesome progress and way over my head 😅

But one thing that in my head would make sense would be to move to version number 3.0.0, after a change of that scale. Another thing I have looked at in the last few days are some of the actions, and i think that a merge on a few of them would be possible as a clean up, and would make sense to do at the same time, at least if you already need an update script for this, if not I'll just add one for that part after.

**Comment by thedist** [comment]
I don't think this requires a major version bump, as it's mostly behind the scenes stuff so my thinking is that we keep this pull request just on this feature and the patch version bump.

For updating actions though, I think what we could do is create an update branch from this main repo, and that way as well as a separate pull request for updating actions I also have some new features planned (such as activator support, and layer tally indicators) and then once all of those features and action changes are added we can make a single upgrade script, major version bump, and merge that branch with the master at the same time.

**Comment by McHauge** [comment]
Sounds like a great idea

**Comment by krocheck** [comment]
Yeah, keep with the current numbering.

On the branch concept, typically that would be a `develop` branch where you drop changes to a point then PR it to main when its time to release.  Then I can review all the changes in one PR.

**Comment by thedist** [comment]
This PR should be good to go. I've tested with large vMix API data sets (for anyone interested vMix seems to split messages that are larger than 65,536 bytes) and it all works fine from what I can test.

**Comment by McHauge** [comment]
after having used/tested this locally, and in a few shows now, and it seems to work wonders together with the new vmix version 23.x.x.66 and beta 24.x.x.x

Therefore I think it's ready and we should include the current version of the module into the core v1.2.9

**Pull request merged**
