### PR TITLE
bugfix for remove_topbar (#105)

### PR DESCRIPTION
**Pull request by krocheck**
This needs to be tested, but conceptually is how to resolve

### CODE REVIEW

**Comment by McHauge** [comment]
hmmm, it's closer to working but not quite. I had to change `var img = new this.createImage()` to `var img = this.createImage()` otherwise I would get a "this.createImage() is not a constructor" in the log.

But with this change, it works in either state, with or without, but if you change it after adding the feedback, it will still crash. and you need to effectively remove the feedbacks, or set them to full or none, in order to disable or enable the top bar again.

**Comment by krocheck** [comment]
that would make sense because of the 'savedIcons` array.  Maybe something like what I just committed to track that setting will help.

**Comment by McHauge** [comment]
same error: `C:\Users\GamingVM\Documents\GitHub\companion\lib\image.js:742
                throw new Error(
                ^

Error: Pixelbuffer for a 72x58 image should be either 12528 or 16704 bytes big. Not 15552
    at image.drawPixelBuffer (C:\Users\GamingVM\Documents\GitHub\companion\lib\image.js:742:9)
    at graphics.drawBankImage (C:\Users\GamingVM\Documents\GitHub\companion\lib\graphics.js:304:11)
    at graphics.drawBank (C:\Users\GamingVM\Documents\GitHub\companion\lib\graphics.js:382:14)
    at graphics.drawPage (C:\Users\GamingVM\Documents\GitHub\companion\lib\graphics.js:397:18)
    at graphics.generate (C:\Users\GamingVM\Documents\GitHub\companion\lib\graphics.js:169:8)
    at EventEmitter.<anonymous> (C:\Users\GamingVM\Documents\GitHub\companion\lib\graphics.js:106:9)
    at EventEmitter.emit (events.js:326:22)
    at Socket.<anonymous> (C:\Users\GamingVM\Documents\GitHub\companion\lib\userconfig.js:59:12)
    at Socket.emit (events.js:314:20)
    at Socket.emitUntyped (C:\Users\GamingVM\Documents\GitHub\companion\node_modules\socket.io\dist\typed-events.js:69:22)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by McHauge** [comment]
works in both states, you just can't change between with and without top bar

**Comment by krocheck** [comment]
hmmm.  I know I can drop a try-catch into that stack to stop the crash, but we don't really have a 'check all feedbacks' method and I'm trying to figure out the best method to pull that off.  What about people that have uploaded 72x58 graphics? Do they get errors when changing this?

**Comment by McHauge** [comment]
No they don't, it does a scaling, if i remember correctly. I was thinking about what if the feedbacks made one for each and the core chose the one that matched the current layout size. Just a thought

**Comment by krocheck** [comment]
That's not quite how this works.  You're using the Image class to draw an image and as the feedback processes its like you're uploading it in realtime to the graphics library to put it in the bank.  To pull that off you would have to run two instances of `indicators` and in your return in the feedback you'd have to provide something like `img64` and `img64-ntb`.  That doesn't seem horrible for your case, but in a module like `shure-wireless` that's drawing many layers for dozens of different looks as rf, audio, and battery changes its quite unreasonable to waste the cpu to draw and the ram to save two copies for an edge case of that setting changing in realtime.  We just need a way to flush them a re-run all the feedbacks.

**Comment by krocheck** [comment]
Can you give the changes I dropped in [companion/fix/image-remove_topbar](https://github.com/bitfocus/companion/tree/fix/image-remove_topbar) a try.

**Comment by McHauge** [comment]
sure 2 min

**Comment by McHauge** [comment]
kinda works, there is no crash now, but the feedback/img only appear again after you have touched the feedbacks on the buttons, just one or two of each type, and the rest comes to life.

**Comment by krocheck** [comment]
Try for me instead in `graphics.js` line 106 moving `system.emit('feedback_check_all')` before `self.generate(true)`.

**Comment by McHauge** [comment]
hmmm, same kind of result, but now all need's to be updated, before any shows up

**Comment by krocheck** [comment]
Pending core PR [#1628](https://github.com/bitfocus/companion/pull/1628) will finally resolve this.

**Comment by thedist** [comment]
Closing PR as this is resolved in v2.0.0

**Pull request closed without merging**
