### PR TITLE
Feat layer tally

### LINKED ISSUE #41: Instance Feedback: Live Input in program/preview
I am not sure if this should be a modification to the existing feedback function or a separate type of feedback.  I would like to be able to set feedback on a button if any input on a multi view input is in the preview/program.  I believe the tally natively works that way so maybe that could be how a new function works.  Tally is Program (set input name) and Tally is Preview (set input name).  Thanks for reading!

### LINKED ISSUE #65: Vmix tally
i was wondering do you have similar issue with tally. When I have set blank or color as input in vmix, tally works ok, but if I set Blackmagic capture device input (DeckLink Duo (1) 1, DeckLink Duo (2) 2, etc...), or i set video file as input, tally does not work anymore. I use vmix 22, and companion 2.1.0

### PR DESCRIPTION
**Pull request by thedist**
Added a layer tally indicator option to Preview/Program feedback. When an input is not directly selected as in preview/program but is layer or overlay in the input that is (even if it's nested within other inputs), the feedback will have the option to display a border or corner indicator that matches the bgColor of the feedback.

Also fixes an issue where versions of vMix prior to v23 lacked the `shortTitle` param on inputs, which would cause a crash when this module tried to access them.

Resolves #41 
Fixes #65

### CODE REVIEW

**Comment by McHauge** [comment]
This will be a welcome addition, but i have one thing, why not a different color option for the border? Just thinking that would give some freedom, but also that might never be used anyway since it won't be on together with the background anyway. Personally i could see a reason for having maybe blue as a border color, since it will give me a feedback, where i can't miss interpret it as if it was fully on

**Comment by McHauge** [comment]
Or did I miss that as an option, haven't read all the way through 😂

**Comment by thedist** [comment]
The indicator uses the bgColor because it's designed to indicate where that input is live, and the shape to indicate that it's a layer and not a the actual input.

For example, in most cases 99% of the time green = thing in preview, red = thing in program. At least for Mix1, I know some productions that use different preview/program colours for mix 2 to 4.

I think adding more colours would just over-complicate things as you need to know at a glance if something is live or not, and if you have blue, or some other colour, it may confuse some people as to if that layer is in preview, or program, for that mix.

**Comment by McHauge** [comment]
Totally understand that, i would just set the default to be the same color, så red for live and green for preview, but haven't used it you so, I can't really talk to much about it 🙈 Will have to see later on after having used it in a produktion

**Comment by thedist** [comment]
If there's a demand for it then it can be submitted as a feature request. I'm just hesitant about over-complicating feedback, as it'll be the 6th option for that feedback and it may not even be used as the user may have the Layer Tally set to none anyway. The companion UI isn't particularly great for neatly handing actions/feedbacks that have lots of options, especially when a button may have more than one action/feedback.

**Comment by McHauge** [comment]
@thedist do you want to add this your self, or just have it on the sideline for a bit?

**Comment by thedist** [comment]
I have someone who's testing it in their current streaming setup and I'm just waiting to see if they have any issues or changes before merging, which I should hopefully be able to do by the end of today/tomorrow.

**Pull request merged**
